FROM node:20-alpine as base

RUN mkdir -p /app
WORKDIR /app

COPY package.json package-lock.json .swcrc /app/
COPY src /app/src
COPY scripts/private.pem /app/

FROM base as build
RUN npm ci && npm cache clean --force
RUN npm i @swc/core -D
RUN npm run build

FROM base as dev
COPY --from=build /app/dist /app/dist
COPY --from=build /app/node_modules /app/node_modules

ENV NODE_ENV="production"
EXPOSE 4444

CMD ["npm", "run", "dev"]