FROM node:21-alpine

RUN mkdir -p /app
WORKDIR /app

COPY package.json package-lock.json .swcrc /app/
COPY src /app/src
COPY scripts/private.pem /app/

RUN npm ci && npm cache clean --force
RUN npm run build
COPY /dist /app/dist

ENV NODE_ENV="production"
EXPOSE 4444

CMD ["npm", "run", "dev"]